### PR TITLE
note to activate plugin

### LINKED ISSUE #12: hint to include plugins in pelicanconf.py
Please include a hint to include plugins=['search'] in the README.MD

- [x] I have searched the [issues](https://github.com/pelican-plugins/search/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

### PR DESCRIPTION
**Pull request by maphew**
# Pull Request Checklist

Resolves: #12 

- [ ] Conformed to **code style guidelines** by running appropriate linting tools
- [x] Updated **documentation** for changed code

### CODE REVIEW

**Comment by maphew** [comment]
As best I can tell the pre-commit error below is not related to this change.
Linter not run because I don't know what that might be for a Markdown only change.

**Comment by justinmayer** [comment]
Hey Matt. Many thanks for the pull request. As I just commented in the issue this PR intends to resolve (#12), the problem with this proposed change is that it isn't quite true. I think perhaps the situation might be better clarified by something like:

```diff
Once Stork has been successfully installed and tested, this plugin can be installed via:

    python -m pip install pelican-search

+ If you are using Pelican 4.5+ with namespace plugins and don’t have a `PLUGINS` setting
+ defined in your configuration, then the Search plugin should be auto-discovered with no further 
+ action required. If, on the other hand, you _do_ have a `PLUGINS` setting defined (because 
+ you also use legacy plugins or because you want to be able to selectively disable 
+ installed plugins), then you must manually add `search` to the `PLUGINS` setting, as 
+ described in the [Plugins section of the Pelican docs](https://docs.getpelican.com/en/latest/plugins.html).
```

**Comment by justinmayer** [comment]
Oh, and I think we can safely ignore the error from `pre-commit.ci`, who seems to be having a sad today.

**Comment by maphew** [comment]
Ahhh, I see. Thanks!

**Pull request closed without merging**
